### ISSUE TITLE
As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

### ISSUE THREAD

**Issue by gudipudipradeep** [pyxll/pyxll-examples#12]
`C:\bamboo\excel>python bitmex.py
Traceback (most recent call last):
  File "C:\bamboo\excel\bitmex.py", line 118, in <module>
    class BitMexRTD(RTD):
  File "C:\bamboo\excel\bitmex.py", line 124, in BitMexRTD
    _bitmex = BitMex(get_event_loop())
  File "C:\bamboo\excel\bitmex.py", line 29, in __init__
    self.__lock = asyncio.Lock(loop=loop)
  File "C:\Program Files\Python310\lib\asyncio\locks.py", line 78, in __init__
    super().__init__(loop=loop)
  File "C:\Program Files\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary`

**Comment by usag1r** [comment]
This should be fixed by simply removing the loop parameter completely as suggested in the pull request #13
